[package]
name = "mojo-colaborativefiltering"
version = "0.1.0"
description = "A Mojo Package"
authors = ["Jose Angel Molina <iosifgmh@gmail.com>"]
license = ""
repository = ""
edition = "2024"
mojo-version = "0.6.1"


[dependencies]